version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nikopa_hambakliinik
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
    - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
    - 6080:8080